checksum: b6f9027fcebcf4f8f21e24fd7fffce0b
summary: This collection focuses on practicing innovation through various
  approaches. It emphasizes leading with purpose to inspire creativity, becoming
  a polyglot programmer to enhance problem-solving skills, embracing a
  disruptive mindset for innovative thinking, and creating beauty in everyday
  projects. The resources cover topics such as purposeful leadership, diverse
  coding skills, rebellious creativity, and design aesthetics.
excerpt: Practice innovation by leading with clear purpose, becoming a polyglot
  programmer, embracing a disruptive mindset, and creating beauty in everyday
  projects. These approaches foster creativity, broaden problem-solving skills,
  and enhance attention to detail.
title: values
articles: []
courses:
  - practice-innovation
